-- efed4262880ad5508da8985a10ca8f05
-- This hash is used for caching, delete to decompile the file again

require( "lua.Lobby.Process.LobbyProcess" )

Lobby.Core.AddProcessForward( LobbyData.UITargets.UI_CPLOBBYLANGAME, LobbyData.UITargets.UI_CPLOBBYLANCUSTOMGAME, function ( f1_arg0, f1_arg1, f1_arg2 )
	return Lobby.ProcessNavigate.ChangeToCPLANCustomGameLobby( f1_arg0, f1_arg1, f1_arg2 )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_CPLOBBYLANGAME, LobbyData.UITargets.UI_MODESELECT, function ( f2_arg0, f2_arg1, f2_arg2 )
	return Lobby.ProcessNavigate.LeaveGameLobby( f2_arg0, f2_arg1, f2_arg2, LuaEnums.LEAVE_WITH_PARTY.WITH, "" )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_CPLOBBYLANCUSTOMGAME, LobbyData.UITargets.UI_CPLOBBYLANGAME, function ( f3_arg0, f3_arg1, f3_arg2 )
	return Lobby.ProcessNavigate.LeaveCPLANGameLobby( f3_arg0, f3_arg1, f3_arg2, LuaEnums.LEAVE_WITH_PARTY.WITH, "" )
end )
Lobby.Core.AddProcessForward( LobbyData.UITargets.UI_CPLOBBYONLINE, LobbyData.UITargets.UI_CPLOBBYONLINECUSTOMGAME, function ( f4_arg0, f4_arg1, f4_arg2 )
	return Lobby.ProcessNavigate.ChangeToCustomGameLobby( f4_arg0, f4_arg1, f4_arg2 )
end )
Lobby.Core.AddProcessForward( LobbyData.UITargets.UI_CPLOBBYONLINE, LobbyData.UITargets.UI_CPLOBBYONLINEPUBLICGAME, function ( f5_arg0, f5_arg1, f5_arg2 )
	return Lobby.ProcessNavigate.ChangeToCPPublicGameLobby( f5_arg0, f5_arg1, f5_arg2 )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_CPLOBBYONLINE, LobbyData.UITargets.UI_MODESELECT, function ( f6_arg0, f6_arg1, f6_arg2, f6_arg3 )
	return Lobby.ProcessNavigate.LeaveGameLobby( f6_arg0, f6_arg1, f6_arg2, f6_arg3 )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_CPLOBBYONLINEPUBLICGAME, LobbyData.UITargets.UI_CPLOBBYONLINE, function ( f7_arg0, f7_arg1, f7_arg2, f7_arg3 )
	return Lobby.ProcessNavigate.ChangeToPrivateGameLobby( f7_arg0, f7_arg1, f7_arg2, f7_arg3 )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_CPLOBBYONLINECUSTOMGAME, LobbyData.UITargets.UI_CPLOBBYONLINE, function ( f8_arg0, f8_arg1, f8_arg2, f8_arg3 )
	return Lobby.ProcessNavigate.ChangeToPrivateGameLobby( f8_arg0, f8_arg1, f8_arg2, f8_arg3 )
end )
Lobby.Core.AddProcessForward( LobbyData.UITargets.UI_CP2LOBBYLANGAME, LobbyData.UITargets.UI_CP2LOBBYLANCUSTOMGAME, function ( f9_arg0, f9_arg1, f9_arg2 )
	return Lobby.ProcessNavigate.ChangeToCPLANCustomGameLobby( f9_arg0, f9_arg1, f9_arg2 )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_CP2LOBBYLANGAME, LobbyData.UITargets.UI_MODESELECT, function ( f10_arg0, f10_arg1, f10_arg2 )
	return Lobby.ProcessNavigate.LeaveGameLobby( f10_arg0, f10_arg1, f10_arg2, LuaEnums.LEAVE_WITH_PARTY.WITHOUT, "" )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_CP2LOBBYLANCUSTOMGAME, LobbyData.UITargets.UI_CP2LOBBYLANGAME, function ( f11_arg0, f11_arg1, f11_arg2, f11_arg3 )
	return Lobby.ProcessNavigate.LeaveCPLANGameLobby( f11_arg0, f11_arg1, f11_arg2, f11_arg3, "" )
end )
Lobby.Core.AddProcessForward( LobbyData.UITargets.UI_CP2LOBBYONLINE, LobbyData.UITargets.UI_CP2LOBBYONLINECUSTOMGAME, function ( f12_arg0, f12_arg1, f12_arg2 )
	return Lobby.ProcessNavigate.ChangeToCustomGameLobby( f12_arg0, f12_arg1, f12_arg2 )
end )
Lobby.Core.AddProcessForward( LobbyData.UITargets.UI_CP2LOBBYONLINE, LobbyData.UITargets.UI_CP2LOBBYONLINEPUBLICGAME, function ( f13_arg0, f13_arg1, f13_arg2 )
	return Lobby.ProcessNavigate.ChangeToCPPublicGameLobby( f13_arg0, f13_arg1, f13_arg2 )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_CP2LOBBYONLINE, LobbyData.UITargets.UI_MODESELECT, function ( f14_arg0, f14_arg1, f14_arg2, f14_arg3 )
	return Lobby.ProcessNavigate.LeaveGameLobby( f14_arg0, f14_arg1, f14_arg2, f14_arg3 )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_CP2LOBBYONLINEPUBLICGAME, LobbyData.UITargets.UI_CP2LOBBYONLINE, function ( f15_arg0, f15_arg1, f15_arg2, f15_arg3 )
	return Lobby.ProcessNavigate.ChangeToPrivateGameLobby( f15_arg0, f15_arg1, f15_arg2, f15_arg3 )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_CP2LOBBYONLINECUSTOMGAME, LobbyData.UITargets.UI_CP2LOBBYONLINE, function ( f16_arg0, f16_arg1, f16_arg2, f16_arg3 )
	return Lobby.ProcessNavigate.ChangeToPrivateGameLobby( f16_arg0, f16_arg1, f16_arg2, f16_arg3 )
end )
Lobby.Core.AddProcessForward( LobbyData.UITargets.UI_DOALOBBYONLINE, LobbyData.UITargets.UI_DOALOBBYONLINEPUBLICGAME, function ( f17_arg0, f17_arg1, f17_arg2 )
	return Lobby.ProcessNavigate.ChangeToCPPublicGameLobby( f17_arg0, f17_arg1, f17_arg2 )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_DOALOBBYONLINE, LobbyData.UITargets.UI_MODESELECT, function ( f18_arg0, f18_arg1, f18_arg2, f18_arg3 )
	return Lobby.ProcessNavigate.LeaveGameLobby( f18_arg0, f18_arg1, f18_arg2, f18_arg3 )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_DOALOBBYONLINEPUBLICGAME, LobbyData.UITargets.UI_DOALOBBYONLINE, function ( f19_arg0, f19_arg1, f19_arg2, f19_arg3 )
	return Lobby.ProcessNavigate.ChangeToPrivateGameLobby( f19_arg0, f19_arg1, f19_arg2, f19_arg3 )
end )
Lobby.Core.AddProcessForward( LobbyData.UITargets.UI_DOALOBBYONLINE, LobbyData.UITargets.UI_CPLOBBYONLINECUSTOMGAME, function ( f20_arg0, f20_arg1, f20_arg2 )
	return Lobby.ProcessNavigate.ChangeToCustomGameLobby( f20_arg0, f20_arg1, f20_arg2 )
end )
Lobby.Core.AddProcessForward( LobbyData.UITargets.UI_DOALOBBYONLINE, LobbyData.UITargets.UI_CPLOBBYONLINEPUBLICGAME, function ( f21_arg0, f21_arg1, f21_arg2 )
	return Lobby.ProcessNavigate.ChangeToCPPublicGameLobby( f21_arg0, f21_arg1, f21_arg2 )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_DOALOBBYLANGAME, LobbyData.UITargets.UI_MODESELECT, function ( f22_arg0, f22_arg1, f22_arg2 )
	return Lobby.ProcessNavigate.LeaveGameLobby( f22_arg0, f22_arg1, f22_arg2, LuaEnums.LEAVE_WITH_PARTY.WITHOUT, "" )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_DOALOBBYLANCUSTOMGAME, LobbyData.UITargets.UI_DOALOBBYLANGAME, function ( f23_arg0, f23_arg1, f23_arg2, f23_arg3 )
	return Lobby.ProcessNavigate.LeaveCPLANGameLobby( f23_arg0, f23_arg1, f23_arg2, f23_arg3, "" )
end )
