require( "lua.Lobby.Process.LobbyProcess" )

Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_ZMLOBBYLANGAME, LobbyData.UITargets.UI_MODESELECT, function ( controller, fromTarget, toTarget )
	return Lobby.ProcessNavigate.LeaveGameLobby( controller, fromTarget, toTarget, LuaEnums.LEAVE_WITH_PARTY.WITHOUT, "" )
end )
Lobby.Core.AddProcessForward( LobbyData.UITargets.UI_ZMLOBBYONLINE, LobbyData.UITargets.UI_ZMLOBBYONLINECUSTOMGAME, function ( controller, fromTarget, toTarget )
	return Lobby.ProcessNavigate.ChangeToCustomGameLobby( controller, fromTarget, toTarget )
end )
Lobby.Core.AddProcessForward( LobbyData.UITargets.UI_ZMLOBBYONLINE, LobbyData.UITargets.UI_ZMLOBBYONLINEPUBLICGAME, function ( controller, fromTarget, toTarget )
	return Lobby.ProcessNavigate.ChangeToPublicGameLobby( controller, fromTarget, toTarget )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_ZMLOBBYONLINE, LobbyData.UITargets.UI_MODESELECT, function ( controller, fromTarget, toTarget )
	return Lobby.ProcessNavigate.LeaveGameLobby( controller, fromTarget, toTarget, LuaEnums.LEAVE_WITH_PARTY.WITHOUT, "" )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_ZMLOBBYONLINEPUBLICGAME, LobbyData.UITargets.UI_ZMLOBBYONLINE, function ( controller, fromTarget, toTarget )
	return Lobby.ProcessNavigate.ChangeToPrivateGameLobby( controller, fromTarget, toTarget, LuaEnums.LEAVE_WITH_PARTY.WITHOUT )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_ZMLOBBYONLINECUSTOMGAME, LobbyData.UITargets.UI_ZMLOBBYONLINE, function ( controller, fromTarget, toTarget )
	return Lobby.ProcessNavigate.ChangeToPrivateGameLobby( controller, fromTarget, toTarget, LuaEnums.LEAVE_WITH_PARTY.WITHOUT )
end )
