require( "lua.Lobby.Process.LobbyProcess" )

Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_CPLOBBYLANGAME, LobbyData.UITargets.UI_MODESELECT, function ( controller, fromTarget, toTarget )
	return Lobby.ProcessNavigate.LeaveGameLobby( controller, fromTarget, toTarget, LuaEnums.LEAVE_WITH_PARTY.WITHOUT, "" )
end )
Lobby.Core.AddProcessForward( LobbyData.UITargets.UI_CPLOBBYONLINE, LobbyData.UITargets.UI_CPLOBBYONLINECUSTOMGAME, function ( controller, fromTarget, toTarget )
	return Lobby.ProcessNavigate.ChangeToCustomGameLobby( controller, fromTarget, toTarget )
end )
Lobby.Core.AddProcessForward( LobbyData.UITargets.UI_CPLOBBYONLINE, LobbyData.UITargets.UI_CPLOBBYONLINEPUBLICGAME, function ( controller, fromTarget, toTarget )
	return Lobby.ProcessNavigate.ChangeToCPPublicGameLobby( controller, fromTarget, toTarget )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_CPLOBBYONLINE, LobbyData.UITargets.UI_MODESELECT, function ( controller, fromTarget, toTarget, withParty )
	return Lobby.ProcessNavigate.LeaveGameLobby( controller, fromTarget, toTarget, withParty )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_CPLOBBYONLINEPUBLICGAME, LobbyData.UITargets.UI_CPLOBBYONLINE, function ( controller, fromTarget, toTarget )
	return Lobby.ProcessNavigate.ChangeToPrivateGameLobby( controller, fromTarget, toTarget, LuaEnums.LEAVE_WITH_PARTY.WITHOUT )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_CPLOBBYONLINECUSTOMGAME, LobbyData.UITargets.UI_CPLOBBYONLINE, function ( controller, fromTarget, toTarget )
	return Lobby.ProcessNavigate.ChangeToPrivateGameLobby( controller, fromTarget, toTarget, LuaEnums.LEAVE_WITH_PARTY.WITHOUT )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_CP2LOBBYLANGAME, LobbyData.UITargets.UI_MODESELECT, function ( controller, fromTarget, toTarget )
	return Lobby.ProcessNavigate.LeaveGameLobby( controller, fromTarget, toTarget, LuaEnums.LEAVE_WITH_PARTY.WITHOUT, "" )
end )
Lobby.Core.AddProcessForward( LobbyData.UITargets.UI_CP2LOBBYONLINE, LobbyData.UITargets.UI_CP2LOBBYONLINECUSTOMGAME, function ( controller, fromTarget, toTarget )
	return Lobby.ProcessNavigate.CreateGameLobby( controller, fromTarget, toTarget )
end )
Lobby.Core.AddProcessForward( LobbyData.UITargets.UI_CP2LOBBYONLINE, LobbyData.UITargets.UI_CP2LOBBYONLINEPUBLICGAME, function ( controller, fromTarget, toTarget )
	return Lobby.ProcessNavigate.ChangeToPublicGameLobby( controller, fromTarget, toTarget )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_CP2LOBBYONLINE, LobbyData.UITargets.UI_MODESELECT, function ( controller, fromTarget, toTarget, withParty )
	return Lobby.ProcessNavigate.LeaveGameLobby( controller, fromTarget, toTarget, withParty )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_CP2LOBBYONLINEPUBLICGAME, LobbyData.UITargets.UI_CP2LOBBYONLINE, function ( controller, fromTarget, toTarget )
	return Lobby.ProcessNavigate.ChangeToPrivateGameLobby( controller, fromTarget, toTarget, LuaEnums.LEAVE_WITH_PARTY.WITHOUT )
end )
Lobby.Core.AddProcessBack( LobbyData.UITargets.UI_CP2LOBBYONLINECUSTOMGAME, LobbyData.UITargets.UI_CP2LOBBYONLINE, function ( controller, fromTarget, toTarget )
	return Lobby.ProcessNavigate.ChangeToPrivateGameLobby( controller, fromTarget, toTarget, LuaEnums.LEAVE_WITH_PARTY.WITHOUT )
end )
